#!/usr/bin/zsh

# Change the color
escape="\e[" # bash -s \033[
color="${escape}1;32m"

# These get changed by parameters
build=false
parent=`pwd`

if [[ ! -z $1 ]]; then
    if [[ $1 == "-b" ]]; then
        build=true
    else
        parent=$1
    fi
fi

if [[ ! -z $2 ]]; then
    if [[ $2 == "-b" ]]; then
        build=true
    else
        parent=$2
    fi
fi

for dir in ${parent}/workbench/*/*/ ; do
    cd $dir
    package="${PWD##*/}"
    echo "${color}Updating ${package}${escape}0m"
    git up
    if [ $build ]; then
        composer up
    fi
done

cd $parent
git up
if [ $build ]; then
    composer up
    brunch build
fi
