#!/bin/bash

ALIAS="$1"
SOURCE="$2"
DEST="$3"

if [ -z $ALIAS ]
then
	echo "You must supply a drush alias group"
	exit 1
fi

if [ -z $SOURCE ]
then
	SOURCE="live"
fi

if [ -z $DEST ]
then
	DEST="local"
fi

SOURCEUSER=$(drush sa @$ALIAS.$SOURCE --component=remote-user);
SOURCEHOST=$(drush sa @$ALIAS.$SOURCE --component=remote-host);
SOURCEFILES=$(drush dd @$ALIAS.$SOURCE:%files);

DESTFILES=$(drush dd @$ALIAS.$DEST:%files);

# Remove everything from %files on destination
if [[ "$DEST" == "local" ]]
then
	cd $DESTFILES;
	rm -rf ./*;
else
	DESTUSER=$(drush sa @$ALIAS.$DEST --component=remote-user);
	DESTHOST=$(drush sa @$ALIAS.$DEST --component=remote-host);
	ssh -t -t $DESTUSER@$DESTHOST <<-EOI
		cd $DESTFILES
		rm -rf ./*;
		exit
	EOI
fi

# Drop all tables in destination DB
drush -y @$ALIAS.$DEST sql-drop

# Copy DB from source to destination
drush -y sql-sync @$ALIAS.$SOURCE @$ALIAS.$DEST --no-cache

# Copy %files from source to destination, excluding generated imagecache, aggegrated CSS and JS
drush -y rsync @$ALIAS.$SOURCE:%files @$ALIAS.$DEST:%files --exclude="styles/*" --exclude="js/*" --exclude="css/*" --progress

# Do any necessary DB updates
drush -y @$ALIAS.$DEST updatedb

# Clear caches
drush @$ALIAS.$DEST cc all

# Revert all features
drush -y @$ALIAS.$DEST fra

# Flush imagecache
drush @$ALIAS.$DEST image-flush --all
