# personal bash stuff

# Define system-wide colours
if [ -f ~/.bash_colours ]; then
    . ~/.bash_colours
fi

# Configure prompt
if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
    if [ -f ~/.bash_set_prompt ]; then
        . ~/.bash_set_prompt
    fi
fi

# Custom bash completions
if [ -f ~/.bash_completion ]; then
    . ~/.bash_completion
fi

# Set up path
export PATH=${PATH}:${HOME}/workspace/android/sdk/platform-tools
export PATH=${PATH}:${HOME}/workspace/android/sdk/tools
export PATH=${PATH}:${HOME}/.bin
export PATH=$PATH:${HOME}/.composer/vendor/bin
export PATH=$PATH:${HOME}/.nodejs/bin

# Custom aliases
alias ll='ls -lh'
alias la='ls -ah'
alias df='df -h'
alias su='su -l'
alias g='git'
alias d='drush'
alias s='sow'
alias v='vagrant'
alias texclean='rm *.backup *.run.xml *.log *.aux *-blx.bib *.dvi'
alias bfg='java -jar bfg.jar'

# Work aliases
if [ -f ~/.c4_aliases ]; then
    . ~/.c4_aliases
fi
