#!/bin/bash

# Simple bash completion for file paths
_rfilecomp() {
    local cur opts myfilepath
    cur="${COMP_WORDS[COMP_CWORD]}"
    myfilepath=$1
    if [ ! -z $2 ]; then
      myfilefilter=$2
    else
      myfilefilter=*
    fi
    opts=`cd $myfilepath ; ls -f $myfilefilter`
    COMPREPLY=`compgen -W "${opts}" -- ${cur}`
}

# Simplebash completion for directory paths
_rdircomp() {
    local cur opts myfilepath
    cur="${COMP_WORDS[COMP_CWORD]}"
    myfilepath=$1
    opts=`cd $myfilepath ; ls -d */`
    COMPREPLY=`compgen -W "${opts}" -- ${cur}`
}
